add books app to project
LemCommunity/lem pull request #12
Opened 2022-12-18 18:54 UTC by Mefpef

add books app to project with configuration in project settings

2022-12-18 18:58 UTC, kstypik requested changes

2022-12-18 18:58 UTC, kstypik commented on backend/config/urls.py
> +    path("api/books", include("backend.apps.books.urls")),
This needs correction. Your path object with your app's URLs must be placed **inside** of urlpatterns list, not outside like right now. Additionally, you have to fix the double static URLs.

2022-12-19 09:09 UTC, Indoxer requested changes
Add __init__.py to books app folder

2022-12-19 18:32 UTC, Indoxer approved these changes

2022-12-19 19:07 UTC, kstypik requested changes

2022-12-19 19:07 UTC, kstypik commented on backend/apps/books/apps.py
> +class ForumConfig(AppConfig):
You've copied too much. The name is incorrect.

2022-12-19 19:36 UTC, closed without merging