5 create base models
LemCommunity/lem pull request #32
Opened 2022-12-21 19:45 UTC by radthenone

comment to review

2022-12-23 11:10 UTC, Indoxer requested changes

2022-12-23 11:10 UTC, Indoxer commented on backend/apps/forum/tests/test_models.py
> +        assert Reply.objects.sum_replies(id=reply_fifty_model_id) == 50
You can also test \_\_str\_\_ methods, regex validators (It is django functionality but your regex not)

2022-12-23 12:11 UTC, Indoxer commented on backend/apps/forum/models.py
> +        verbose_name="Reply updated",
-||-

2022-12-23 12:11 UTC, Indoxer commented on backend/apps/forum/models.py
> +        auto_now_add=True,
You can add verbose_name

2022-12-25 22:17 UTC, Indoxer commented on backend/apps/forum/models.py
> +        self.body = markdown_text(self.body)
not html

2022-12-25 22:25 UTC, Indoxer commented on backend/apps/forum/tests/test_models.py
> +    def test_post_model(self, post_model) -> None:
Testing everything may be an option (in pure TDD it is required), but I think we can make our lives easier and test things that can break easily

2022-12-26 11:14 UTC, radthenone commented on backend/apps/forum/apps.py
> +        request_finished.connect(signals.category_name)
ok i removed request_finished lines.

2022-12-26 14:44 UTC, radthenone commented on backend/apps/forum/apps.py
> +        request_finished.connect(signals.category_name)
ok only    `    def ready(self):
        from backend.apps.forum import signals` stay here

2022-12-26 16:20 UTC, radthenone commented on backend/apps/forum/managers.py
> +class ReplyManager(models.Manager):
Post now use count but work with manager, Reply now used @property method

2022-12-26 16:27 UTC, radthenone commented on backend/apps/forum/models.py
> +                message="Input must contain only alphabetic characters",
done, ^[a-zA-Z]+$

2022-12-26 17:12 UTC, radthenone commented on backend/apps/forum/models.py
> +        return self.name
ok i added this with Meta class in all models

2022-12-27 13:26 UTC, Indoxer commented on backend/apps/forum/managers.py
> +    def sum_posts(self):
This is unnecessary, to much abstraction

2022-12-27 14:50 UTC, Indoxer requested changes

2022-12-27 14:50 UTC, Indoxer commented on backend/apps/forum/tests/factories.py
> +fake = Fake()
In my opinion currently is little mishmash here, you use sometimes raw Faker and sometimes Faker wrapper from factory boy

2022-12-27 14:50 UTC, Indoxer commented on backend/apps/forum/models.py
> +    def slugify_function(self, content):
Death code, you don't use this, AutoSlugField has built-in slugify function

2022-12-27 14:50 UTC, Indoxer commented on backend/apps/forum/tests/factories.py
> +    slug = title
It is not valid slug, you can use LazyAttribute or PostGenerationMethodCall and built-in function to slugify from django extension

2022-12-27 14:50 UTC, Indoxer commented on backend/apps/forum/utils.py
> +            mark_text = str(markdowner.convert(text))
This library cannot convert many lines?

2022-12-30 01:52 UTC, Indoxer approved these changes

2022-12-30 11:01 UTC, merged