create review manager
LemCommunity/lem pull request #47
Opened 2023-01-03 18:24 UTC by maciej-MKan

This is my first piece of code. I wrote a simple review manager to check the ability to navigate the project. So.. don't kill me.

2023-01-06 19:23 UTC, Indoxer requested changes

2023-01-06 19:23 UTC, Indoxer commented on backend/apps/books/managers.py
> +    def all_reviews(self):
```
from backend.apps.books.models import Review

# it breaks DRY and it is confusing. You have the same thing 2 times.
Review.objects.all_reviews() 
Review.objects.all() # it also works
```

2023-01-06 22:11 UTC, maciej-MKan commented on backend/apps/books/managers.py
> +    def all_reviews(self):
I removed the all_reviews method for not duplicate functionality.

2023-01-22 19:05 UTC, kwiats reviewed
ok

2023-01-22 19:06 UTC, kwiats approved these changes
lgfm

2023-01-22 20:12 UTC, merged